# Generated by Django 4.2.7 on 2024-01-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_quantity_order_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='quantities',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
