# Generated by Django 4.2.7 on 2024-01-26 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_cart_order_quantities_remove_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantities',
            new_name='quantity',
        ),
    ]
